name: Mirror repo to GitLab

on: [push, pull_request, delete]

jobs:
  call-nss-ops-mirror-workflow:
    uses: Nunkyl/test-nss-ops/.github/workflows/mirror-repo.yml@main
    with:
      GITLAB_URL: 'https://gitlab.actcognitive.org/LizLutsenko/tourism.git'
    secrets: inherit
    
#    

                  