name: Mirror repo to GitLab

on: [push, pull_request, delete]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.actcognitive.org/LizLutsenko/tourism'
          GIT_USERNAME: LizLutsenko
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}